settings {
   logfile    = "/tmp/lsyncd_fate.log",
   statusFile = "/tmp/lsyncd_fate.status",
   nodaemon   = true,
}
local user_home = os.getenv("HOME")
sync {
    source  = user_home .. "/git/bga-fate/",
    target  = user_home .. "/Develop/bga/remote/fate/",
    default.rsync,
    delay  = 1,
    exclude = { ".git", ".project", ".settings" , ".buildpath", "node_modules",  "img/game*.png", "*.tmp*", "* *", "*.out",  ".phpunit.result.cache", "staging" , "*.cpart", "*.part"},
    rsync     = { 
        omit_dir_times = true
    }
}
